title: "CSE Technical Onboarding"
description: "New hire technical onboarding exercise"
remote_theme: benc-uk/theme-msdark
hide_github: true
hide_tagline: true
favicon: https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/microsoft/310/laptop_1f4bb.png
